const actions = {
  SET_CURRENT_PAGE : 'SET_CURRENT_PAGE',
  SET_MAX_RESULTS : 'SET_MAX_RESULTS',
  SET_STATUS_FILTER : 'SET_STATUS_FILTER',
  SET_SORT_BY : 'SET_SORT_BY',
  SET_SEARCH_TERM : 'SET_SEARCH_TERM',
  SET_PAYMENTS : 'SET_PAYMENTS',
  ADD_PAYMENT : 'ADD_PAYMENT',
  EDIT_PAYMENT : 'EDIT_PAYMENT',
  DELETE_PAYMENT: 'DELETE_PAYMENT'
};

export default actions;